# Copyright (c) 2022 Raseel.city Platform to Present
# All right reserved

version: "3.3"

services:
  postgres:
    image: postgres:14-alpine3.16
    hostname: postgres
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: raseel
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    restart: unless-stopped
    ports:
      - 127.0.0.1:5432:5432
    networks:
      - keycloak_network

  keycloak:
    build:
      context: .
    hostname: raseel-keycloak
    container_name: raseel-keycloak
    environment:
      #Database Configuration
      #KC_DB: postgres
      KC_DB_URL: 'jdbc:postgresql://postgres/raseel'
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
      #KC_DB_SCHEMA: kc
      KC_DB_SCHEMA: public

      #Hostname Configuration
      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT_HTTPS: 'true'

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_USER: user
      KEYCLOAK_PASSWORD: user

      # Other env
      JAVA_OPTS_APPEND: -Xms2048m -Xmx4096m
    entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev"]
    ports:
      - 127.0.0.1:8443:8443
      - 127.0.0.1:8080:8080
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - keycloak_network
volumes:
  postgres_data:
    external:
      true
networks:
  keycloak_network:
